name: nelsonnet-wait-times
base: core22
version: '0.1.0'
summary: Wait Times for Disney World Attractions
description: |
  A small Tauri application to display wait times for Disney World attractions as a gift to my wife
  (because she loves Disney and wait times).

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  nelsonnet-wait-times:
    command: usr/bin/nelsonnet-wait-times
    desktop: usr/share/applications/nelsonnet-wait-times.desktop
    extensions: [gnome]
    plugs:
     - network
    daemon: simple

architectures:
    - build-on: [arm64]
    - build-on: [amd64]

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      npm install
      rustup default stable
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=nelsonnet-wait-times|Icon=/usr/share/icons/hicolor/32x32/apps/nelsonnet-wait-times.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/nelsonnet-wait-times.desktop